import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:driversense_app/core/config/env_config.dart';
import 'package:driversense_app/core/storage/local_storage.dart';

// This file will be generated by injectable_generator
// import 'package:driversense_app/core/di/injection.config.dart';

final GetIt getIt = GetIt.instance;

/// Configure dependency injection
@InjectableInit(preferRelativeImports: true)
Future<void> configureDependencies(EnvConfig config) async {
  // Register environment config
  getIt.registerSingleton<EnvConfig>(config);

  // Initialize local storage
  final localStorage = LocalStorage();
  await localStorage.init();
  getIt.registerSingleton<LocalStorage>(localStorage);

  // Initialize the generated dependencies
  // getIt.init(environment: config.environment.name);

  // Manual registrations for core services
  _registerCoreDependencies();
  _registerDataSources();
  _registerRepositories();
  _registerUseCases();
  _registerBlocs();
}

void _registerCoreDependencies() {
  // These would normally be generated by injectable
  // But we register them manually for clarity

  // Secure storage
  if (!getIt.isRegistered<SecureStorage>()) {
    getIt.registerLazySingleton<SecureStorage>(() => SecureStorage());
  }

  // Network info
  if (!getIt.isRegistered<NetworkInfo>()) {
    getIt.registerLazySingleton<NetworkInfo>(() => NetworkInfoImpl());
  }

  // API client
  if (!getIt.isRegistered<ApiClient>()) {
    getIt.registerLazySingleton<ApiClient>(
      () => ApiClient(
        getIt<SecureStorage>(),
        getIt<EnvConfig>(),
      ),
    );
  }

  // Database
  if (!getIt.isRegistered<AppDatabase>()) {
    getIt.registerLazySingleton<AppDatabase>(() => AppDatabase());
  }

  // Services
  if (!getIt.isRegistered<ConnectivityService>()) {
    getIt.registerLazySingleton<ConnectivityService>(
      () => ConnectivityService(getIt<NetworkInfo>()),
    );
  }

  if (!getIt.isRegistered<NotificationService>()) {
    getIt.registerLazySingleton<NotificationService>(
      () => NotificationService(),
    );
  }

  if (!getIt.isRegistered<SyncService>()) {
    getIt.registerLazySingleton<SyncService>(
      () => SyncService(
        getIt<ConnectivityService>(),
        getIt<AppDatabase>(),
        getIt<ApiClient>(),
      ),
    );
  }

  if (!getIt.isRegistered<LocationService>()) {
    getIt.registerLazySingleton<LocationService>(
      () => LocationService(),
    );
  }

  // Router
  if (!getIt.isRegistered<AuthGuard>()) {
    getIt.registerLazySingleton<AuthGuard>(
      () => AuthGuard(
        getIt<SecureStorage>(),
        getIt<LocalStorage>(),
      ),
    );
  }

  if (!getIt.isRegistered<AppRouter>()) {
    getIt.registerLazySingleton<AppRouter>(
      () => AppRouter(getIt<AuthGuard>()),
    );
  }
}

void _registerDataSources() {
  // Auth
  if (!getIt.isRegistered<AuthRemoteDatasource>()) {
    getIt.registerLazySingleton<AuthRemoteDatasource>(
      () => AuthRemoteDatasourceImpl(getIt<ApiClient>()),
    );
  }

  if (!getIt.isRegistered<AuthLocalDatasource>()) {
    getIt.registerLazySingleton<AuthLocalDatasource>(
      () => AuthLocalDatasourceImpl(
        getIt<SecureStorage>(),
        getIt<LocalStorage>(),
      ),
    );
  }

  // Check
  if (!getIt.isRegistered<CheckRemoteDatasource>()) {
    getIt.registerLazySingleton<CheckRemoteDatasource>(
      () => CheckRemoteDatasourceImpl(getIt<ApiClient>()),
    );
  }

  if (!getIt.isRegistered<CheckLocalDatasource>()) {
    getIt.registerLazySingleton<CheckLocalDatasource>(
      () => CheckLocalDatasourceImpl(getIt<AppDatabase>()),
    );
  }

  // Tracking
  if (!getIt.isRegistered<TrackingRemoteDatasource>()) {
    getIt.registerLazySingleton<TrackingRemoteDatasource>(
      () => TrackingRemoteDatasourceImpl(getIt<ApiClient>()),
    );
  }

  if (!getIt.isRegistered<TrackingLocalDatasource>()) {
    getIt.registerLazySingleton<TrackingLocalDatasource>(
      () => TrackingLocalDatasourceImpl(getIt<AppDatabase>()),
    );
  }
}

void _registerRepositories() {
  // Auth
  if (!getIt.isRegistered<AuthRepository>()) {
    getIt.registerLazySingleton<AuthRepository>(
      () => AuthRepositoryImpl(
        getIt<AuthRemoteDatasource>(),
        getIt<AuthLocalDatasource>(),
        getIt<NetworkInfo>(),
      ),
    );
  }

  // Check
  if (!getIt.isRegistered<CheckRepository>()) {
    getIt.registerLazySingleton<CheckRepository>(
      () => CheckRepositoryImpl(
        getIt<CheckRemoteDatasource>(),
        getIt<CheckLocalDatasource>(),
        getIt<NetworkInfo>(),
      ),
    );
  }

  // Tracking
  if (!getIt.isRegistered<TrackingRepository>()) {
    getIt.registerLazySingleton<TrackingRepository>(
      () => TrackingRepositoryImpl(
        getIt<TrackingRemoteDatasource>(),
        getIt<TrackingLocalDatasource>(),
        getIt<NetworkInfo>(),
      ),
    );
  }
}

void _registerUseCases() {
  // Auth
  if (!getIt.isRegistered<LoginUseCase>()) {
    getIt.registerLazySingleton<LoginUseCase>(
      () => LoginUseCase(getIt<AuthRepository>()),
    );
  }

  if (!getIt.isRegistered<LogoutUseCase>()) {
    getIt.registerLazySingleton<LogoutUseCase>(
      () => LogoutUseCase(getIt<AuthRepository>()),
    );
  }

  // Check
  if (!getIt.isRegistered<GetQuestionsUseCase>()) {
    getIt.registerLazySingleton<GetQuestionsUseCase>(
      () => GetQuestionsUseCase(getIt<CheckRepository>()),
    );
  }

  if (!getIt.isRegistered<SubmitStartCheckUseCase>()) {
    getIt.registerLazySingleton<SubmitStartCheckUseCase>(
      () => SubmitStartCheckUseCase(getIt<CheckRepository>()),
    );
  }

  if (!getIt.isRegistered<SubmitEndCheckUseCase>()) {
    getIt.registerLazySingleton<SubmitEndCheckUseCase>(
      () => SubmitEndCheckUseCase(getIt<CheckRepository>()),
    );
  }

  // Tracking
  if (!getIt.isRegistered<StartTrackingUseCase>()) {
    getIt.registerLazySingleton<StartTrackingUseCase>(
      () => StartTrackingUseCase(getIt<TrackingRepository>()),
    );
  }

  if (!getIt.isRegistered<StopTrackingUseCase>()) {
    getIt.registerLazySingleton<StopTrackingUseCase>(
      () => StopTrackingUseCase(getIt<TrackingRepository>()),
    );
  }
}

void _registerBlocs() {
  // Auth
  if (!getIt.isRegistered<AuthBloc>()) {
    getIt.registerFactory<AuthBloc>(
      () => AuthBloc(
        getIt<LoginUseCase>(),
        getIt<LogoutUseCase>(),
        getIt<AuthLocalDatasource>(),
      ),
    );
  }

  // Check
  if (!getIt.isRegistered<CheckBloc>()) {
    getIt.registerFactory<CheckBloc>(
      () => CheckBloc(
        getIt<GetQuestionsUseCase>(),
        getIt<SubmitStartCheckUseCase>(),
        getIt<SubmitEndCheckUseCase>(),
        getIt<CheckLocalDatasource>(),
      ),
    );
  }

  // Tracking
  if (!getIt.isRegistered<TrackingBloc>()) {
    getIt.registerFactory<TrackingBloc>(
      () => TrackingBloc(
        getIt<StartTrackingUseCase>(),
        getIt<StopTrackingUseCase>(),
        getIt<TrackingLocalDatasource>(),
        getIt<LocationService>(),
      ),
    );
  }
}

// Forward imports for types used in registration
// These would be actual imports in a real project
import 'package:driversense_app/core/storage/secure_storage.dart';
import 'package:driversense_app/core/network/network_info.dart';
import 'package:driversense_app/core/network/api_client.dart';
import 'package:driversense_app/core/storage/database/app_database.dart';
import 'package:driversense_app/core/router/app_router.dart';
import 'package:driversense_app/core/router/route_guards.dart';
import 'package:driversense_app/shared/services/connectivity_service.dart';
import 'package:driversense_app/shared/services/notification_service.dart';
import 'package:driversense_app/shared/services/sync_service.dart';
import 'package:driversense_app/shared/services/location_service.dart';
import 'package:driversense_app/features/auth/data/datasources/auth_remote_datasource.dart';
import 'package:driversense_app/features/auth/data/datasources/auth_local_datasource.dart';
import 'package:driversense_app/features/auth/data/repositories/auth_repository_impl.dart';
import 'package:driversense_app/features/auth/domain/repositories/auth_repository.dart';
import 'package:driversense_app/features/auth/domain/usecases/login_usecase.dart';
import 'package:driversense_app/features/auth/domain/usecases/logout_usecase.dart';
import 'package:driversense_app/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:driversense_app/features/check/data/datasources/check_remote_datasource.dart';
import 'package:driversense_app/features/check/data/datasources/check_local_datasource.dart';
import 'package:driversense_app/features/check/data/repositories/check_repository_impl.dart';
import 'package:driversense_app/features/check/domain/repositories/check_repository.dart';
import 'package:driversense_app/features/check/domain/usecases/get_questions_usecase.dart';
import 'package:driversense_app/features/check/domain/usecases/submit_start_check_usecase.dart';
import 'package:driversense_app/features/check/domain/usecases/submit_end_check_usecase.dart';
import 'package:driversense_app/features/check/presentation/bloc/check_bloc.dart';
import 'package:driversense_app/features/tracking/data/datasources/tracking_remote_datasource.dart';
import 'package:driversense_app/features/tracking/data/datasources/tracking_local_datasource.dart';
import 'package:driversense_app/features/tracking/data/repositories/tracking_repository_impl.dart';
import 'package:driversense_app/features/tracking/domain/repositories/tracking_repository.dart';
import 'package:driversense_app/features/tracking/domain/usecases/start_tracking_usecase.dart';
import 'package:driversense_app/features/tracking/domain/usecases/stop_tracking_usecase.dart';
import 'package:driversense_app/features/tracking/presentation/bloc/tracking_bloc.dart';
